package analyzer_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mentasystems/gox/pkg/analyzer"
	_ "github.com/mentasystems/gox/pkg/analyzers/errcheck"
)

const dropErr = "\nimport \"os\"\n\nfunc F() { os.Remove(\"x\") }\n"

func TestRun_skipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	license := strings.Repeat("// Licensed under the Example License.\n", 25)
	files := map[string]string{
		"go.mod": "module example.test/m\n\ngo 1.25\n",
		// Marker after a 25-line header: still generated per the Go
		// convention (it precedes the package clause).
		"g/long_header.go": license + "\n// Code generated by tool. DO NOT EDIT.\n\npackage g\n" + dropErr,
		"g2/short.go":      "// Code generated by tool. DO NOT EDIT.\n\npackage g2\n" + dropErr,
		// Marker after the package clause does not count.
		"h/late.go": "package h\n\n// Code generated by tool. DO NOT EDIT.\n" + dropErr,
		"u/user.go": "package u\n" + dropErr,
	}
	for name, body := range files {
		path := filepath.Join(dir, name)
		if mkErr := os.MkdirAll(filepath.Dir(path), 0o755); mkErr != nil {
			t.Fatal(mkErr)
		}
		if wErr := os.WriteFile(path, []byte(body), 0o644); wErr != nil {
			t.Fatal(wErr)
		}
	}
	t.Chdir(dir)

	var errcheck []*analyzer.Analyzer
	for _, a := range analyzer.All() {
		if a.Name == "errcheck" {
			errcheck = append(errcheck, a)
		}
	}
	issues, _, err := analyzer.Run([]string{"./..."}, errcheck, analyzer.RunOptions{})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	got := map[string]bool{}
	for _, is := range issues {
		got[filepath.Base(filepath.Dir(is.Pos.Filename))] = true
	}
	for _, pkg := range []string{"g", "g2"} {
		if got[pkg] {
			t.Errorf("issue reported in generated package %s", pkg)
		}
	}
	for _, pkg := range []string{"h", "u"} {
		if !got[pkg] {
			t.Errorf("expected an issue in non-generated package %s, got %v", pkg, issues)
		}
	}
}
